version: '3'

services:
  backend:
    build: ./backend
    container_name: node-backend
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGDATABASE=testdb
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
  
  #grafana:
   # image: grafana/grafana
    #container_name: grafana
    #environment:
     # - GF_SECURITY_ADMIN_PASSWORD=admin
    #ports:
     # - "3001:3000"
    #depends_on:
    #  - prometheus
